---
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: "./tsconfig.json"
  extraFileExtensions: [".svelte"]

env:
  es2022: true
  browser: true

extends:
  - plugin:svelte/recommended
  - plugin:svelte/prettier
  - plugin:prettier/recommended

plugins:
  - svelte
  - "@typescript-eslint"
  - prettier

overrides:
  - files: ["*.svelte"]
    parser: svelte-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
