---
parser: @typescript-eslint/parser
parserOptions:
  sourceType: module

env:
  es2022: true
  browser: true

plugins:
  - svelte3
  - @typescript-eslint

overrides:
  - files: ["*.svelte"]
    processor: "svelte3/svelte3"

settings:
  # load TypeScript as peer dependency
  svelte3/typescript: true
